version: "3.7"

services:
    # image project
    app:
    image: "myapp:latest"
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./site:/www
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - default

# database mysql
    db:
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3310}:3310'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_TCP_PORT: 3310
    volumes:
        - 'db:/var/lib/mysql'
    networks:
        - default
    healthcheck:
        test:
            - CMD
            - mysqladmin
            - ping
            - '-p${DB_PASSWORD}'
        retries: 3
        timeout: 5s

 # servidor web nginx       
  web:
    image: nginx:latest
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./site:/www
    - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
    - app

volumes:
  db:

networks:
  default:
