version: "3.7"

services:
  # image project
  app:
    image: "myapp:latest"
    build:
      context: .
    depends_on:
      - db_mysql
      - db_postgres
    volumes:
      - ./site:/www
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - default

  # database mysql
  db_mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT_MYSQL:-3310}:3310'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_MYSQL}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE_MYSQL}'
      MYSQL_USER: '${DB_USERNAME_MYSQL}'
      MYSQL_PASSWORD: '${DB_PASSWORD_MYSQL}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_TCP_PORT: 3310
    volumes:
      - 'db_mysql:/var/lib/mysql'
    networks:
      - default
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD_MYSQL}'
      retries: 3
      timeout: 5s

  # database postgresql
  db_postgres:
    image: 'postgres:latest'
    ports:
      - '${FORWARD_DB_PORT_POSTGRES:-5432}:5432'
    environment:
      POSTGRES_USER: '${DB_USERNAME_POSTGRES}'
      POSTGRES_PASSWORD: '${DB_PASSWORD_POSTGRES}'
      POSTGRES_DB: '${DB_DATABASE_POSTGRES}'
    volumes:
      - 'db_postgres:/var/lib/postgresql/data'
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME_POSTGRES}"]
      retries: 3
      timeout: 5s

  # servidor web nginx
  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./site:/www
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

volumes:
  db_mysql:
  db_postgres:

networks:
  default:
