version: '3.8' # Define a versão do docker-compose a ser utilizada

services:
  # Serviço do PHP com Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel:/var/www/html  # Mapeia o diretório local para o container
    ports:
      - "8000:80"  # Porta exposta para acessar o Laravel localmente
    networks:
      - laravel_network
    depends_on:
      - mysql

  # Serviço do MySQL
  mysql:
    image: mysql:8.0 # Usando a imagem oficial do MySQL
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Define a senha do root do MySQL
      MYSQL_DATABASE: laravel_db         # Cria um banco de dados ao iniciar o container
      MYSQL_USER: laravel_user           # Define o usuário do MySQL
      MYSQL_PASSWORD: laravel_password   # Define a senha do usuário
    volumes:
      - mysql_data:/var/lib/mysql  # Volume persistente para os dados do MySQL
    ports:
      - "3306:3306"  # Porta exposta para acesso ao MySQL
    networks:
      - laravel_network

  # Serviço do phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin # Usando a imagem oficial do phpMyAdmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: mysql # Conecta ao serviço MySQL pelo nome do container
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"  # Porta exposta para acessar o phpMyAdmin
    depends_on:
      - mysql
    networks:
      - laravel_network

# Definindo volumes persistentes
volumes:
  mysql_data:

# Definindo uma rede personalizada para os containers
networks:
  laravel_network:
